
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/anaconda3/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/opt/homebrew/bin/"
      - "/var/folders/kp/2kghwrrx17172ldwk_dr29gr0000gn/T/.tmpBZBmOV/"
      - "/opt/homebrew/opt/binutils/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/luket/.local/bin/"
      - "/Users/luket/.spicetify/"
      - "/Users/luket/.vscode/extensions/openai.chatgpt-0.4.35-darwin-arm64/bin/macos-aarch64/"
    searched_directories:
      - "/opt/anaconda3/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/anaconda3/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/opt/homebrew/bin"
        - "/var/folders/kp/2kghwrrx17172ldwk_dr29gr0000gn/T/.tmpBZBmOV"
        - "/opt/homebrew/opt/binutils/bin"
        - "/opt/anaconda3/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/opt/homebrew/sbin"
        - "/Users/luket/.local/bin"
        - "/Users/luket/.spicetify"
        - "/Users/luket/.vscode/extensions/openai.chatgpt-0.4.35-darwin-arm64/bin/macos-aarch64"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.0.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/opt/anaconda3/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/opt/homebrew/bin/"
      - "/var/folders/kp/2kghwrrx17172ldwk_dr29gr0000gn/T/.tmpBZBmOV/"
      - "/opt/homebrew/opt/binutils/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/luket/.local/bin/"
      - "/Users/luket/.spicetify/"
      - "/Users/luket/.vscode/extensions/openai.chatgpt-0.4.35-darwin-arm64/bin/macos-aarch64/"
    searched_directories:
      - "/opt/anaconda3/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/opt/anaconda3/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/opt/homebrew/bin"
        - "/var/folders/kp/2kghwrrx17172ldwk_dr29gr0000gn/T/.tmpBZBmOV"
        - "/opt/homebrew/opt/binutils/bin"
        - "/opt/anaconda3/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/opt/homebrew/sbin"
        - "/Users/luket/.local/bin"
        - "/Users/luket/.spicetify"
        - "/Users/luket/.vscode/extensions/openai.chatgpt-0.4.35-darwin-arm64/bin/macos-aarch64"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
